export const flightDetails = {
  route: "DAC → JFK",
  tripType: "Round Trip",
  dates: "25 Mar - 4 Apr 2023",
  stops: "1 Stop",
  totalDuration: "33h 20m",
  segments: [
    {
      segment: "first",
      duration: "12 hr 20 min",
      from: "DAC",
      to: "DXB",
      fromTime: "07:30 PM",
      fromDate: "28 Mar, Friday",
      toTime: "08:50 AM",
      toDate: "29 Mar, Saturday",
      airline: "Turkish Airlines",
      flightNumber: "TUR467",
      aircraft: "Airbus Industrie 737-800-738",
      cabinClass: "ECONOMY-Y (O)",
      isDestination: false,
      segmentName: "Departure from Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      terminal: "Terminal 1",
      notice: `Technical stoppage at Malpensa International Airport (Milano).
                Before booking this flight please check your visa requirements
                as per your nationality`,
    },
    {
      segment: "second",
      duration: "12 hr 20 min",
      from: "DAC",
      to: "DXB",
      fromTime: "07:30 PM",
      fromDate: "28 Mar, Friday",
      toTime: "08:50 AM",
      toDate: "29 Mar, Saturday",
      airline: "Turkish Airlines",
      flightNumber: "TUR467",
      aircraft: "Airbus Industrie 737-800-738",
      cabinClass: "ECONOMY-Y (O)",
      isDestination: false,
      segmentName: "Departure from Dhaka",
      airport: "Dubai International Airport",
      terminal: "",
      notice: "",
    },
    {
      segment: "second",
      duration: "12 hr 20 min",
      from: "DAC",
      to: "DXB",
      fromTime: "07:30 PM",
      fromDate: "28 Mar, Friday",
      toTime: "08:50 AM",
      toDate: "29 Mar, Saturday",
      airline: "Turkish Airlines",
      flightNumber: "TUR467",
      aircraft: "Airbus Industrie 737-800-738",
      cabinClass: "ECONOMY-Y (O)",
      isDestination: true,
      segmentName: "Destination at New York",
      airport: "John F Kennedy International Airport",
      terminal: "Terminal 4",
      notice: "",
    },
  ],
};
